= Zielsetzung

Ziel der vorliegenden Arbeit ist es, einen KI-gestützten Lösungsansatz zu entwickeln, der die Qualität von User Stories innerhalb der Abteilung Digital Solutions verbessert. Im Mittelpunkt steht dabei die Frage, wie unvollständige oder unklare User Stories bereits vor dem eigentlichen Refinement erkannt werden können.

Dazu wird ein Rovo-Agent entwickelt, der automatisch ausgelöst wird, sobald eine User Story einem Sprint hinzugefügt oder bearbeitet wird. Der Agent soll die jeweilige Story mit einer in Confluence hinterlegten Referenz-Vorlage vergleichen und prüfen, ob die wichtigsten Qualitätsanforderungen erfüllt sind. Dazu gehören insbesondere ein eindeutiger Titel, eine ausreichende Beschreibung, ein nachvollziehbarer fachlicher Nutzen, überprüfbare Akzeptanzkriterien sowie technische Hinweise.

Werden diese Anforderungen nicht erfüllt, soll der Agent die erkannten Probleme automatisch als Kommentar dokumentieren. Zusätzlich soll er konkrete Verbesserungsvorschläge und gezielte Rückfragen formulieren, damit die Story bereits vor dem Refinement ergänzt werden kann. Dadurch soll erreicht werden, dass fehlende Informationen früher sichtbar werden und weniger Abstimmungen im späteren Refinement notwendig sind.

Der entwickelte Agent soll die Stories dabei jedoch nicht eigenständig verändern. Die fachliche Entscheidung über mögliche Anpassungen verbleibt weiterhin beim Product Owner beziehungsweise bei den verantwortlichen Mitarbeitenden. Dieses Vorgehen entspricht dem Grundgedanken KI-gestützter Assistenzsysteme, bei denen die KI Vorschläge liefert, während die endgültige Entscheidung weiterhin durch den Menschen getroffen wird @daugherty2024human.

  Darüber hinaus soll der entwickelte Lösungsansatz dazu beitragen, dass die in Confluence vorhandenen Vorlagen und Qualitätsstandards konsequenter genutzt werden. Die Referenz-Vorlage kann dabei je nach Fachbereich angepasst werden. Dadurch soll der Agent langfristig nicht nur für einzelne Test-Stories, sondern grundsätzlich für unterschiedliche Bereiche innerhalb des Unternehmens eingesetzt werden können. Gleichzeitig entspricht dies dem Ansatz von KI-Agenten, die vorhandene Informationen aus verschiedenen Systemen verknüpfen und dadurch unterstützende Aufgaben im Arbeitsprozess übernehmen @koch2025ki.
