= Methodik
Zur Bearbeitung der Problemstellung wurde ein praxisorientiertes Vorgehen gewählt. Ziel war es, einen Lösungsansatz zu entwickeln, der sich ohne grundlegende Änderungen in die bestehende Arbeitsweise der Abteilung integrieren lässt. Die Vorgehensweise orientiert sich am Problemlösungszyklus nach Ahrens und umfasst die Analyse der Ausgangssituation, die Entwicklung eines Lösungsansatzes, dessen prototypische Erprobung sowie die anschließende Bewertung @ahrens2012gliederung.

Ausgangspunkt war zunächst die Analyse der bestehenden User Stories innerhalb der Abteilung. Dabei zeigte sich, dass sich bestimmte Qualitätsmängel regelmäßig wiederholen. Besonders häufig traten unpräzise Titel, fehlende Beschreibungen, unvollständige Akzeptanzkriterien sowie fehlende technische Hinweise auf. Diese Schwachstellen wurden als Grundlage für die Entwicklung des Lösungsansatzes verwendet.

Anschließend wurde eine bereits vorhandene User Story ausgewählt, die durch den Scrum Master als qualitativ hochwertig bewertet wurde. Auf Basis dieser Story wurde in Confluence eine allgemeine Referenz-Vorlage erstellt. Die Vorlage enthält die Abschnitte „Titel“, „Beschreibung“, „Warum?“, „Akzeptanzkriterien“, „Technische Hinweise“, „Offene Fragen“ und „Definition of Done“. Dadurch wird sichergestellt, dass jede User Story nach derselben Struktur beurteilt werden kann. Ein Auszug der verwendeten Referenz-Vorlage befindet sich im Anhang A.1.

Die Referenz-Vorlage dient als Grundlage für den entwickelten Rovo-Agenten. Der Agent wurde in der Jira-Testumgebung „Playground“ eingerichtet. Zusätzlich wurde ein Trigger definiert, der automatisch ausgelöst wird, sobald eine Story einem Sprint hinzugefügt oder bearbeitet wird. Nach der Auslösung vergleicht der Agent die jeweilige Story mit der in Confluence hinterlegten Referenz-Vorlage und erstellt anschließend einen Kommentar mit Verbesserungsvorschlägen und Rückfragen.

Die Entscheidung für dieses Vorgehen wurde bewusst getroffen. Grundsätzlich wären auch andere Methoden möglich gewesen. So hätte beispielsweise eine manuelle Checkliste verwendet werden können, um neue User Stories vor dem Refinement zu prüfen. Der Vorteil einer solchen Methode läge in ihrer einfachen Umsetzung. Gleichzeitig wäre die Prüfung jedoch weiterhin von der jeweiligen Person abhängig. Dadurch könnten unterschiedliche Qualitätsmaßstäbe entstehen und wichtige Informationen trotz vorhandener Checkliste übersehen werden. Darüber hinaus würde eine manuelle Prüfung zusätzlichen Zeitaufwand verursachen.

Ebenso wäre es möglich gewesen, unvollständige User Stories erst im eigentlichen Refinement zu erkennen und dort gemeinsam zu ergänzen. Diese Vorgehensweise entspricht der bisherigen Praxis innerhalb der Abteilung. Sie besitzt jedoch den Nachteil, dass fehlende Informationen erst sehr spät sichtbar werden. Dadurch verlängern sich die Refinement-Meetings, zusätzliche Rückfragen entstehen und die Vergabe von Story Points wird erschwert.

Interviews oder Umfragen mit Mitarbeitenden wurden ebenfalls nicht durchgeführt. Zwar hätten sie zusätzliche Einschätzungen zur aktuellen Situation liefern können, sie wären jedoch nur eingeschränkt geeignet gewesen, um die tatsächliche Wirkung des entwickelten Lösungsansatzes zu bewerten. Da innerhalb des Unternehmens bislang keine praktischen Erfahrungen mit Rovo vorlagen, hätten die Ergebnisse überwiegend auf Erwartungen und Vermutungen basiert.

Aus diesen Gründen wurde ein prototypischer Ansatz gewählt. Der Vorteil dieser Methode besteht darin, dass der entwickelte Agent unmittelbar innerhalb der vorhandenen Arbeitsumgebung getestet werden kann. Dadurch lässt sich überprüfen, ob der Lösungsansatz grundsätzlich geeignet ist, typische Qualitätsmängel frühzeitig zu erkennen und die vorhandenen Vorlagen konsequenter anzuwenden.

Gleichzeitig besitzt der gewählte Ansatz auch wirtschaftliche Vorteile. Da Jira, Confluence und Atlassian Rovo bereits im Unternehmen vorhanden sind, entstehen keine zusätzlichen Lizenz- oder Einführungskosten. Ebenso müssen keine neuen Systeme eingeführt oder Schnittstellen geschaffen werden. Der entwickelte Lösungsansatz nutzt somit die bestehende Infrastruktur und kann ohne größeren organisatorischen Aufwand umgesetzt werden. Dies stellt gegenüber alternativen Werkzeugen oder externen Lösungen einen wesentlichen Vorteil dar.

Der entwickelte Rovo-Agent bietet zudem den Vorteil, dass jede User Story automatisch und nach denselben Kriterien geprüft wird. Dadurch entsteht eine einheitliche Bewertung unabhängig von der jeweiligen Person. Gleichzeitig werden fehlende Informationen bereits vor dem Refinement sichtbar. Dadurch könnten sich Rückfragen, Nacharbeit und Unsicherheiten bei der Vergabe von Story Points reduzieren.

Der Agent nimmt jedoch bewusst keine automatischen Änderungen an der Story vor. Stattdessen werden die Ergebnisse ausschließlich als Kommentar im Namen des Rovo-Agenten in Jira hinterlegt. Die fachliche Entscheidung über mögliche Anpassungen verbleibt weiterhin beim Product Owner beziehungsweise bei den verantwortlichen Mitarbeitenden. Dieses Vorgehen wurde gewählt, da der Agent zwar strukturelle und logische Probleme erkennen kann, jedoch nicht über denselben fachlichen Wissensstand wie die beteiligten Personen verfügt. Durch die Kombination aus automatisierter Analyse und menschlicher Entscheidungskompetenz lässt sich das Ziel der Arbeit am besten erreichen @daugherty2024human.

Die Bewertung des entwickelten Lösungsansatzes erfolgt anhand vier qualitativer Kriterien. Erstens wird untersucht, ob der Agent typische Qualitätsmängel vollständig erkennt. Zweitens wird bewertet, ob die erzeugten Hinweise und Rückfragen nachvollziehbar und verständlich formuliert sind. Drittens wird betrachtet, inwiefern der Ansatz im betrieblichen Kontext praktisch und wirtschaftlich einsetzbar erscheint. Viertens werden die Grenzen und Risiken des entwickelten Lösungsansatzes reflektiert. Diese Kriterien bilden die Grundlage für die Bewertung in Kapitel 6.
