= Methodik

Die vorliegende Arbeit orientiert sich methodisch am erweiterten Problemlösungszyklus nach Ahrens. Dieser beschreibt eine strukturierte Vorgehensweise zur Bearbeitung praxisorientierter Problemstellungen, bei der ausgehend von einer konkreten betrieblichen Ausgangssituation schrittweise ein geeigneter Lösungsansatz entwickelt und bewertet wird (Ahrens, 2012). 

Im Mittelpunkt der Arbeit steht die Frage, wie der Atlassian-Rovo-KI-Assistent genutzt werden kann, um die Qualität von User Stories bereits vor dem Refinementprozess zu verbessern. Da für diese Fragestellung bislang weder ein bestehender Lösungsansatz noch Erfahrungen aus dem Regelbetrieb vorliegen, ist die Arbeit als konzeptionell-explorative Untersuchung einzuordnen.

Ziel der Arbeit ist nicht die empirische Untersuchung eines bereits etablierten Systems, sondern die Entwicklung und erste Erprobung eines neuen Lösungsansatzes im Unternehmenskontext. Aus diesem Grund wurde bewusst keine quantitative Methode gewählt. Eine statistische Auswertung oder eine Vergleichsstudie wäre erst dann sinnvoll möglich, wenn der entwickelte Rovo-Agent bereits über einen längeren Zeitraum im produktiven Einsatz wäre und entsprechende Daten zur Verfügung stünden.

Auch andere methodische Ansätze wurden verworfen. Eine Befragung von Mitarbeitenden hätte zwar Einschätzungen zum aktuellen Refinementprozess liefern können, wäre jedoch nicht ausreichend gewesen, um die tatsächliche Funktionsweise und Eignung des entwickelten Agenten zu bewerten. Ebenso wäre eine rein theoretische Literaturarbeit nicht zielführend gewesen, da der Schwerpunkt der Arbeit auf einer konkreten betrieblichen Problemstellung und deren praktischer Lösung liegt.

Stattdessen eignet sich für die vorliegende Problemstellung ein konzeptioneller Ansatz, bei dem zunächst die Ausgangssituation analysiert, anschließend Anforderungen aus Literatur und betrieblicher Praxis abgeleitet und darauf aufbauend ein Lösungsansatz entwickelt wird. Dieses Vorgehen entspricht dem erweiterten Problemlösungszyklus nach Ahrens, da Theorie und Praxis systematisch miteinander verbunden werden (Ahrens, 2012). 

Zu Beginn der Arbeit erfolgt daher eine Analyse des bestehenden Prozesses innerhalb der Abteilung DS. Hierbei wird untersucht, wie User Stories aktuell erstellt, priorisiert und im Refinement verwendet werden. Im Mittelpunkt stehen insbesondere die Ursachen für den erhöhten Abstimmungsaufwand. Dabei zeigt sich, dass viele User Stories unvollständig formuliert sind, widersprüchliche Akzeptanzkriterien enthalten oder wichtige Informationen wie technische Details und Business Value fehlen.

Auf Basis dieser Analyse werden anschließend Anforderungen an qualitativ hochwertige User Stories abgeleitet. Hierzu werden sowohl theoretische Grundlagen als auch betriebliche Anforderungen herangezogen. Als theoretischer Bezugsrahmen dienen insbesondere die Beschreibung von User Stories nach Cohn sowie das INVEST-Prinzip zur Bewertung ihrer Qualität. Nach Cohn erfüllen User Stories ihren Zweck nur dann, wenn sie eine ausreichende Grundlage für Kommunikation, Aufwandsschätzung und Umsetzung bieten. Das INVEST-Prinzip konkretisiert diese Anforderungen durch die Kriterien Independent, Negotiable, Valuable, Estimable, Small und Testable (Cohn, 2004; Buglione & Abran, 2013).  

Zusätzlich wird eine im Unternehmen bereits vorhandene User Story verwendet, die durch den Scrum Master als qualitativ hochwertige Referenz definiert wurde. Diese Referenz-Story enthält die gewünschte Struktur, den erforderlichen Detaillierungsgrad sowie die notwendigen Bestandteile einer vollständigen User Story. Sie dient dem entwickelten Agenten als Vergleichsgrundlage. Durch die Kombination aus theoretischen Qualitätskriterien und einer betrieblichen Referenz wird sichergestellt, dass der entwickelte Lösungsansatz sowohl wissenschaftlich fundiert als auch praktisch anwendbar ist.

Anschließend wird der eigentliche Lösungsansatz entwickelt und praktisch umgesetzt. Hierzu wird in der Jira-Testumgebung „Playground“ ein Rovo-Agent konfiguriert. Die Nutzung einer Testumgebung wurde bewusst gewählt, da der Agent dadurch unter realitätsnahen Bedingungen erprobt werden kann, ohne bestehende Prozesse oder produktive Projekte zu beeinflussen.

Der Agent wird so eingerichtet, dass er automatisch ausgelöst wird, sobald eine User Story einem Sprint hinzugefügt oder nachträglich bearbeitet wird. Nach der Auslösung greift der Agent auf die Inhalte der jeweiligen Story sowie auf die hinterlegte Referenz-Story in Confluence zu. Anschließend erfolgt ein Vergleich zwischen beiden Inhalten.

Im Rahmen dieser Analyse prüft der Agent insbesondere, ob die Story vollständig und verständlich formuliert ist, ob Akzeptanzkriterien vorhanden und logisch konsistent sind und ob wichtige Bestandteile wie Business Value, technische Details oder Abhängigkeiten fehlen. Darüber hinaus untersucht der Agent, ob möglicherweise bereits ähnliche Stories existieren und somit doppelte Anforderungen vorliegen. Die Nutzung des in Jira und Confluence integrierten Rovo-Agenten wurde gewählt, da bereits alle notwendigen Systeme im Unternehmen vorhanden sind und somit kein zusätzliches Werkzeug eingeführt werden muss (Atlassian, 2022). 

Die Ergebnisse der Analyse werden nicht automatisch in die User Story übernommen. Stattdessen erstellt der Agent einen Kommentar, in dem die erkannten Schwachstellen, offene Rückfragen und konkrete Verbesserungsvorschläge dokumentiert werden. Diese Form des Outputs wurde bewusst gewählt, da der Agent nicht über denselben fachlichen Wissensstand wie die beteiligten Mitarbeitenden verfügt. Eine automatische Änderung der Story könnte daher zu fehlerhaften oder unpassenden Anpassungen führen. Durch die Ausgabe eines Kommentars verbleibt die fachliche Entscheidung weiterhin beim Product Owner beziehungsweise bei den verantwortlichen Mitarbeitenden.

Die Bewertung des entwickelten Lösungsansatzes erfolgt abschließend anhand qualitativer Kriterien. Untersucht wird insbesondere, ob der Agent typische Schwachstellen zuverlässig erkennt, ob die Hinweise verständlich und nachvollziehbar formuliert sind und ob die erzeugten Kommentare geeignet erscheinen, den Abstimmungsaufwand im Refinementprozess zu reduzieren. Diese Form der qualitativen Bewertung wurde gewählt, da aufgrund der bisher ausschließlich testweisen Erprobung noch keine ausreichende Datenbasis für eine quantitative Bewertung vorliegt.

Insgesamt ermöglicht die gewählte Methodik, Theorie und betriebliche Praxis miteinander zu verbinden, den entwickelten Lösungsansatz unter realitätsnahen Bedingungen zu erproben und gleichzeitig die Grenzen der eigenen Untersuchung transparent darzustellen. Damit entspricht das Vorgehen sowohl den Anforderungen des erweiterten Problemlösungszyklus nach Ahrens als auch den Zielsetzungen der vorliegenden Arbeit.
