= Fazit und Ausblick

Ziel der vorliegenden Arbeit war es, die Qualität von User Stories innerhalb der Abteilung Digital Solutions zu verbessern und dadurch den Refinementprozess effizienter zu gestalten. Die Situationsanalyse zeigte, dass unvollständige User Stories, fehlende Akzeptanzkriterien und die inkonsequente Nutzung vorhandener Vorlagen die Hauptursachen für Rückfragen, Unsicherheiten bei der Aufwandsschätzung und Verzögerungen im Refinementprozess darstellen.

Zur Lösung dieser Problemstellung wurde ein Rovo-Agent entwickelt, der automatisch ausgelöst wird, sobald eine User Story einem Sprint hinzugefügt oder bearbeitet wird. Der Agent vergleicht die jeweilige Story mit einer in Confluence hinterlegten Referenz-Vorlage und prüft, ob die definierten Qualitätsanforderungen erfüllt sind.

Im Rahmen der prototypischen Erprobung in der Jira-Testumgebung „Playground“ zeigte sich, dass der Agent typische Schwachstellen wie unpräzise Titel, fehlende Beschreibungen, nicht vorhandene Akzeptanzkriterien und fehlende technische Hinweise erkennen kann. Gleichzeitig erstellt der Agent konkrete Verbesserungsvorschläge und Rückfragen, ohne eigenständig Änderungen an der Story vorzunehmen. Dadurch bleibt die fachliche Verantwortung weiterhin bei den beteiligten Mitarbeitenden beziehungsweise beim Product Owner.

Der entwickelte Lösungsansatz besitzt darüber hinaus das Potenzial, die vorhandenen Vorlagen und Qualitätsstandards konsequenter in den Arbeitsprozess zu integrieren. Da die Referenz-Vorlage je nach Fachbereich angepasst werden kann, lässt sich der Agent nicht nur für einzelne Testfälle, sondern grundsätzlich für unterschiedliche Bereiche innerhalb des Unternehmens einsetzen.

Auch wirtschaftlich erscheint der entwickelte Ansatz sinnvoll. Da Jira, Confluence und Atlassian Rovo bereits im Unternehmen vorhanden sind, entstehen keine zusätzlichen Lizenz- oder Einführungskosten. Gleichzeitig erscheint es plausibel, dass sich durch vollständigere User Stories Rückfragen, Nacharbeit und Unsicherheiten bei der Vergabe von Story Points reduzieren könnten. Eine empirische Bestätigung dieser Effekte ist im Rahmen der vorliegenden Arbeit jedoch noch nicht möglich.

Trotz der positiven Ergebnisse weist die Arbeit auch Grenzen auf. Der Agent wurde bislang ausschließlich in der Testumgebung erprobt und kann fachliche Entscheidungen nicht selbstständig treffen. Zudem basiert die Bewertung lediglich auf einzelnen Test-Stories, sodass keine allgemeingültigen Aussagen über die tatsächliche Wirkung im Arbeitsalltag getroffen werden können.

Für die Zukunft bietet sich daher an, den entwickelten Agenten schrittweise in den realen Arbeitsalltag zu integrieren und seine Wirkung über mehrere Sprints hinweg zu untersuchen. Dabei sollte insbesondere analysiert werden, ob sich die Anzahl der Rückfragen, die Dauer von Refinement-Meetings sowie die Genauigkeit der Story-Point-Schätzung messbar verändern. Darüber hinaus wäre es sinnvoll, unterschiedliche Referenz-Vorlagen für verschiedene Fachbereiche zu entwickeln und zu prüfen, wie gut der Agent mit diesen unterschiedlichen Anforderungen umgehen kann.

Zusammenfassend deutet die Arbeit darauf hin, dass ein KI-gestütztes Assistenzsystem einen sinnvollen Beitrag zur Verbesserung der Qualität von User Stories leisten kann. Insbesondere die Kombination aus automatisierter Analyse und menschlicher Entscheidungskompetenz erscheint geeignet, den Refinementprozess langfristig zu unterstützen.
